### ISSUE TITLE
New Version of Facebook Apps Breaks new feeds

### ISSUE THREAD

**Issue by Ketziel** [Ketziel/socialator#8]
Facebook has updated to version 2.4. 
This has deprecated /statuses which is being used to retrieve the feed.

A potential replacement is /feed.

**Comment by jburleigh1** [comment]
you'll want to change line 195, swap 'statuses' out for 'feeds' and that will allow it to work with the latest version - best solution would be add a conditional to allow you to define wether or not your app is using a version greater than 2.3.

**Comment by Ketziel** [comment]
This can now be specified using the `facebookVersion` parameter.
Leave blank when using the newest version of the facebook api.
